version: "1"
projects:
  - name: WAW
    environments:
      - name: Production
        services:
          - type: web
            name: WAW
            runtime: docker
            repo: https://github.com/salihchelebi/waw
            plan: free
            region: frankfurt
            branch: main
            dockerContext: .
            dockerfilePath: ./Dockerfile.render.blueprint
            dockerCommand: sh scripts/render-start.sh
            healthCheckPath: /api/v1/ping
            autoDeployTrigger: commit
            disk:
              name: flowise-data
              mountPath: /var/data
              sizeGB: 1
            envVars:
              - key: DATABASE_URL
                sync: false
              - key: PORT
                sync: false
